version: '3.8'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  
      MYSQL_DATABASE: stationSki
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - app-network

  backend-container:
    image: bedouizied/stationdeski:1.0.0
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stationSki
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
  mysql_config:
networks:
  app-network:
    driver: bridge
